// GENERATED BY THE CODEGEN SCRIPT
import typeDef from "./Test.graphql";
import resolvers from "./TestResolvers";
import { Test, ITest } from "./TestModel";

export { typeDef, resolvers, Test, ITest };
