// GENERATED BY THE CODEGEN SCRIPT
import { Test } from "./TestModel";
import { User } from "../User";

export default {
  Test: {
    owner: (test) => {
      return User.findById(test.owner);
    },
  },
  Query: {
    allTest: () => {
      return Test.find({});
    },
    Test: (_root, args) => {
      return Test.findById(args.id);
    },
  },
  Mutation: {
    createTest: (_root, args) => {
      return Test.create(args.input);
    },
    updateTest: (_root, args) => {
      return Test.findByIdAndUpdate(args.id, args.input, { runValidators: true, new: true });
    },
    deleteTest: (_root, args) => {
      return Test.findByIdAndDelete(args.id);
    },
  },
};
