// GENERATED BY THE CODEGEN SCRIPT
import { Schema, model, Document } from "mongoose";
import schema from "./schema";
import { IUser } from "../User";

const CompanySchema = new Schema(schema.definition, schema.options);

export interface ICompany extends Document {
  name: string;
  owningUser: IUser;
  businessOfficialId?: string;
  vatNumber?: string;
}

export const Company = model<ICompany>("Company", CompanySchema);
