// GENERATED BY THE CODEGEN SCRIPT
import { Schema, model, Document } from "mongoose";
import { IUser } from "../User";
import schema from "./schema";

const CompanySchema = new Schema(schema.definition, schema.options);

export interface ICompany extends Document {
  name: string;
  owningUser: IUser;
  businessOfficialId?: string;
  vatNumber?: string;
  createdAt: Date;
  updatedAt: Date;
}

export const Company = model<ICompany>("Company", CompanySchema);
