// GENERATED BY THE CODEGEN SCRIPT
import { Company } from "./CompanyModel";
import { User } from "../User";

export default {
  Company: {
    owningUser: (company) => {
      return User.findById(company.owningUser);
    },
  },
  Query: {
    allCompany: () => {
      return Company.find({});
    },
    Company: (_root, args) => {
      return Company.findById(args.id);
    },
  },
  Mutation: {
    createCompany: (_root, args) => {
      return Company.create(args.input);
    },
    updateCompany: (_root, args) => {
      return Company.findByIdAndUpdate(args.id, args.input, { runValidators: true, new: true });
    },
    deleteCompany: (_root, args) => {
      return Company.findByIdAndDelete(args.id);
    },
  },
};
