// GENERATED BY THE CODEGEN SCRIPT
import typeDef from "./Company.graphql";
import resolvers from "./CompanyResolvers";
import { Company, ICompany } from "./CompanyModel";

export { typeDef, resolvers, Company, ICompany };
