// GENERATED BY THE CODEGEN SCRIPT
import typeDef from "./Object.graphql";
import resolvers from "./ObjectResolvers";
import { Object, IObject } from "./ObjectModel";

export { typeDef, resolvers, Object, IObject };
