// GENERATED BY THE CODEGEN SCRIPT
import { Schema, model, Document } from "mongoose";
import schema from "./schema";

const ObjectSchema = new Schema(schema.definition, schema.options);

export interface IObject extends Document {
  $IOBJECT
}

export const Object = model<IObject>("Object", ObjectSchema);
