// GENERATED BY THE CODEGEN SCRIPT
import { Object } from "./ObjectModel";
$IMPORTS

export default {
  Object: {
    $GRAPHQL_OBJECT_QUERY
  },
  Query: {
    allObject: () => {
      return Object.find({});
    },
    Object: (_root, args) => {
      return Object.findById(args.id);
    },
  },
  Mutation: {
    createObject: (_root, args) => {
      return Object.create(args.input);
    },
    updateObject: (_root, args) => {
      return Object.findByIdAndUpdate(args.id, args.input, { runValidators: true, new: true });
    },
    deleteObject: (_root, args) => {
      return Object.findByIdAndDelete(args.id);
    },
  },
};
