// GENERATED BY THE CODEGEN SCRIPT
import { merge } from "lodash";

import { typeDef as Company, resolvers as CompanyResolvers } from "../models/Company";
import { typeDef as User, resolvers as UserResolvers } from "../models/User";

const typeDefs = [Company, User];
const resolvers = merge(CompanyResolvers, UserResolvers);

export { typeDefs, resolvers };
